apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-postgres
  template:
    metadata:
      labels:
        app: service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5433
          envFrom:
            - configMapRef:
                name: service-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: service-postgres-pv-claim
