apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-slave-validity-factor 2
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
    maxmemory 100mb
    maxmemory-policy allkeys-lru