apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: "redis:6.0"
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
          volumeMounts:
            - name: conf
              mountPath: "/etc/redis/redis.conf"
              subPath: redis.conf
              readOnly: true
      volumes:
        - name: conf
          configMap:
            name: redis-config
