apiVersion: v1
kind: Service
metadata:
  name: fingerprint
spec:
  type: NodePort
  selector:
    app: fingerprint
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30037