apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingerprint-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fingerprint
  template:
    metadata:
      labels:
        app: fingerprint
    spec:
      containers:
      - name: fingerprint
        image: fingerprint:6.0
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8091
