apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  ports:
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: service:6.0
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 81
