apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
      nodePort: 30036

    # - port: 80
    #   targetPort: 81
