apiVersion: v1
kind: Service
metadata:
  name: fingerprint-postgres
  labels:
    app: fingerprint-postgres
spec:
  ports:
    - port: 5433
      targetPort: 5432
  selector:
   app: fingerprint-postgres